#Verbose during prediction
verbose: False

img_size: 720
epochs: 84
batch_size: 8

#for training
mode: 'train'
data: "./dataset_kitty/yolo/dataset.yaml"
output: "yolov8n_mot_ch"
model: weights/yolov8n.pt #download pretrained model on ultralytics
resume: False
