#Verbose during prediction
verbose: False

img_size: 720
epochs: 10
batch_size: 8

#for training
mode: 'train'
data: "./dataset_kitty/yolo/dataset.yaml"
output: "yolov8n_seg"
model: weights/yolov8n-seg.pt #download pretrained model on ultralytics
resume: False
